"""empty message

Revision ID: 20b453ab1d93
Revises: 82b33aedb96b
Create Date: 2023-03-25 14:22:52.389162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20b453ab1d93"
down_revision = "82b33aedb96b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbox_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.String(), nullable=False))
        batch_op.add_column(
            sa.Column("event_unique_identifier", sa.String(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("payload", postgresql.JSON(astext_type=sa.Text()), nullable=False)
        )
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
        )
        batch_op.add_column(
            sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("delivery_errors", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("delivery_paused_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbox_records", schema=None) as batch_op:
        batch_op.drop_column("delivery_paused_at")
        batch_op.drop_column("delivery_errors")
        batch_op.drop_column("delivered_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("payload")
        batch_op.drop_column("event_unique_identifier")
        batch_op.drop_column("event_id")

    # ### end Alembic commands ###
