"""empty message

Revision ID: 7b51930894e5
Revises: 20b453ab1d93
Create Date: 2023-04-07 18:32:25.199874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7b51930894e5'
down_revision = '20b453ab1d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("debezium_outbox_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.String(), nullable=False))
        batch_op.add_column(
            sa.Column("event_unique_identifier", sa.String(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("payload", postgresql.JSON(astext_type=sa.Text()), nullable=False)
        )
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbox_records", schema=None) as batch_op:
        batch_op.drop_column("created_at")
        batch_op.drop_column("payload")
        batch_op.drop_column("event_unique_identifier")
        batch_op.drop_column("event_id")

    # ### end Alembic commands ###
