"""empty message

Revision ID: 82b33aedb96b
Revises: 
Create Date: 2023-02-19 18:34:58.033621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b33aedb96b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.drop_column('quantity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
