version: "3.8"
services:
  db:
    image: postgres:11.8
    container_name: "bookstore_database"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./deploy/postgres/postgres-data:/var/lib/postgresql/data
      - ./deploy/postgres/local_db:/docker-entrypoint-initdb.d
    env_file:
      - .env
      - .secrets.env
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        development: "True"
    restart: on-failure
    ports:
      - "${FLASK_RUN_PORT}:8001"
    links:
      - db
    volumes:
      - .:/app
    command: "pipenv run flask run --host=${FLASK_RUN_HOST} --port=${FLASK_RUN_PORT}"
    depends_on:
      - db
