version: "3.8"
services:
  transactional-worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        development: "True"
    restart: on-failure
    command: "pipenv run flask transactional-outbox-worker"
    networks:
      - kafka
    depends_on:
      - db
    env_file:
      - .env
      - .secrets.env
    volumes:
      - ./src/bookstore.log:/bookstore.log
      - ./src/bookstore_errors.log:/bookstore_errors.log
      - ./src/publication_data.log:/publication_data.log

networks:
  kafka:
    external: true
    name: kafka
