version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        development: "True"
    restart: on-failure
    ports:
      - "8001:${FLASK_RUN_PORT}"
    links:
      - db
    volumes:
      - .:/app
    command: "pipenv run flask run --host=${FLASK_RUN_HOST} --port=${FLASK_RUN_PORT}"
  db:
    image: postgres:11.8
    container_name: "bookstore_database"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "54321:${DB_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./deploy/local_db:/docker-entrypoint-initdb.d
    env_file:
      - .env
