version: "3.8"
services:
  outbox-connector:
    image: debezium/connect:latest
    container_name: outbox-connector
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=broker_a:9092,broker_b:9092,broker_c:9092
      - GROUP_ID=debezium_outbox
      - CONFIG_STORAGE_TOPIC=outbox-connector-configs
      - OFFSET_STORAGE_TOPIC=outbox-connector-offsets
    networks:
      - kafka
    volumes:
      - logs:/kafka/logs
      - config:/kafka/config
  debezium-ui:
    image: debezium/debezium-ui
    ports:
      - 8081:8080
    environment:
      - KAFKA_CONNECT_URIS=http://outbox-connector:8083
    depends_on:
      - outbox-connector
    networks:
      - kafka

volumes:
  logs:
  config:

networks:
  kafka:
    external: true
    name: kafka
