import settings as st


class Config:
	SECRET_KEY = st.SECRET_KEY
	POSTGRES_USER = st.DB_USERNAME
	POSTGRES_PASSWORD = st.DB_PASSWORD
	POSTGRES_HOST = st.DB_HOST
	POSTGRES_PORT = st.DB_PORT
	POSTGRES_DB_NAME = st.DB_NAME
	SQLALCHEMY_DATABASE_URI = st.DB_URI
	SQLALCHEMY_TRACK_MODIFICATIONS = False
